### ISSUE TITLE
Simple link button

### ISSUE THREAD

**Issue by grzegab** [arteneo/forge#9]
Link as simplie as can be

**Comment by awtyklo** [comment]
We spoke about using Link from 'react-router-dom` right?

Is it still the case? Can we close this issue?

**Comment by grzegab** [comment]
That is correct, we can close it :)

Od: Wtykło Arkadiusz <notifications@github.com> <notifications@github.com>
Odpowiedz: arteneo/forge
<reply@reply.github.com>
<reply@reply.github.com>
Data: 25 lutego 2021 at 13:14:17
Do: arteneo/forge <forge@noreply.github.com> <forge@noreply.github.com>
DW: GrzeGab <grzegorz.gabryel@gmail.com> <grzegorz.gabryel@gmail.com>,
Author <author@noreply.github.com> <author@noreply.github.com>
Temat:  Re: [arteneo/forge] Simple link button (#9)

We spoke about using Link from 'react-router-dom` right?

Is it still the case? Can we close this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arteneo/forge/issues/9#issuecomment-785852212>, or
unsubscribe
